sudo: false
language: node_js
node_js:
- '7'
git:
  depth: 3
notifications:
  slack:
    secure: pruiXBfZe4Mq3oiEVU9RYirkFd6Sz4kYyruahuiCpW8mnaV4XwVNSYPuxTAUlYowpZOrh85eCKWEBvcxxXqC+9icc2J+ReL5v2B57tfhQ9QIWwoYLccD+ndCpuQMW6tIqWB0F9k/QchP2awhqakuwLcI+AZgNXv1G4LDuHOEz/8TdOaFMlqDRQcxl3M1yyWNftw9V1adCkF1GMSVsRaiK7i0S7xkwtYCBXT0iBchYtuFWcwdASMVgFnHJaGB3j97RkVAc8bndrcENGm5TCdCSXiQwLNtStYjJgOHn4l545dfwK6dHiH9iChalbPVIzEtEEIyJM52Ug2+/iEJ/aaSn8K1c05/wfEpe0XbZIplAktZOFRjT2vlkf31MHoLynBf2sYIxEr/DF5QFqQz7tmRIlwl0AVyEaAqkeJM2KRZEhTpR4FhdAxupqqPQzKo33IyGEzD615Xr7hmFNwGDX1CRxql0nTQ/Ilyf+2PeQRY6Tiw7RsUolyxkIOMViuRdhR2l+fphxP/HUbqsDfv73PyCzyYzX56pXJIwIxJ00E2AfU29jQ28RAckjhwE/OLTtRcvQ8rsLfMNdZfhAyP0gZD0e11rrqoJxYxtfWbLbd0pjGgHRiLSARwYoKAxlzpTFFyqaMwZgEemoPZin0w11cgYMIsS5HRTBbLtQivYNL+iRo=
